<?php

namespace App\Constants;

class VucemCatalogs
{
    public static $monedas = [
        // --- PÁGINA 1 ---
        'AED' => 'Dirham de los Emiratos Árabes Unidos',
        'AFN' => 'Afgani afgano',
        'ALL' => 'Lek albanés',
        'AMD' => 'Dram armenio',
        'ANG' => 'Florín antillano neerlandés',
        'AOA' => 'Kwanza angoleño',
        'ARS' => 'Peso argentino',
        'AUD' => 'Dólar australiano',
        'AWG' => 'Florín arubeño',
        'AZM' => 'Manat azerbaiyano',
        'BAM' => 'Marco convertible de Bosnia-Herzegovina',
        'BBD' => 'Dólar de Barbados',
        'BDT' => 'Taka de Bangladesh',
        'BGN' => 'Lev búlgaro',
        'BHD' => 'Dinar bahreiní',
        'BIF' => 'Franco burundés',
        'BMD' => 'Dòlar de Bermuda',
        'BND' => 'Dòlar de Brunéi',
        'BOB' => 'Boliviano',
        'BOV' => 'Mvdol boliviano (código de fondos)',
        'BRL' => 'Real brasileño',
        'BSD' => 'Dólar bahameño',
        'BTN' => 'Ngultrum de Bután',
        'BWP' => 'Pula de Botsuana',
        'BYR' => 'Rublo bielorruso',
        'BZD' => 'Dólar de Belice',
        'CAD' => 'Dólar canadiense',
        'CDF' => 'Franco congoleño',
        'CHF' => 'Franco suizo',
        'CLF' => 'Unidades de fomento chilenas (código de fondos)',
        'CLP' => 'Peso chileno',
        'CNY' => 'Yuan Renminbi de China',
        'COP' => 'Peso colombiano',
        'COU' => 'Unidad de valor real colombiana (añadida al COP)',
        'CRC' => 'Colón costarricense',
        'CSD' => 'Dinar serbio (Reemplazado por RSD el 25 de octubre de 2006)',
        'CUP' => 'Peso cubano',
        'CUC' => 'Peso cubano convertible',
        'CVE' => 'Escudo caboverdiano',
        'CYP' => 'Libra chipriota',
        'CZK' => 'Koruna checa',
        'DJF' => 'Franco yibutiano',
        'DKK' => 'Corona danesa',
        'DOP' => 'Peso dominicano',

        // --- PÁGINA 2 ---
        'DZD' => 'Dinar algerino',
        'EEK' => 'Corona estonia',
        'EGP' => 'Libra egipcia',
        'ERN' => 'Nakfa eritreo',
        'ETB' => 'Birr etíope',
        'EUR' => 'Euro',
        'FJD' => 'Dólar fijiano',
        'FKP' => 'Libra malvinense',
        'GBP' => 'Libra esterlina (libra de Gran Bretaña)',
        'GEL' => 'Lari georgiano',
        'GHS' => 'Cedi ghanés',
        'GIP' => 'Libra de Gibraltar',
        'GMD' => 'Dalasi gambiano',
        'GNF' => 'Franco guineano',
        'GTQ' => 'Quetzal guatemalteco',
        'GYD' => 'Dólar guyanés',
        'HKD' => 'Dólar de Hong Kong',
        'HNL' => 'Lempira hondureño',
        'HRK' => 'Kuna croata',
        'HTG' => 'Gourde haitiano',
        'HUF' => 'Forint húngaro',
        'IDR' => 'Rupiah indonesia',
        'ILS' => 'Nuevo shéquel israelí',
        'INR' => 'Rupia india',
        'IQD' => 'Dinar iraquí',
        'IRR' => 'Rial iraní',
        'ISK' => 'Króna islandesa',
        'JMD' => 'Dólar jamaicano',
        'JOD' => 'Dinar jordano',
        'JPY' => 'Yen japonés',
        'KES' => 'Chelín keniata',
        'KGS' => 'Som kirguís (de Kirguistán)',
        'KHR' => 'Riel camboyano',
        'KMF' => 'Franco comoriano (de Comoras)',
        'KPW' => 'Won norcoreano',
        'KRW' => 'Won surcoreano',
        'KWD' => 'Dinar kuwaití',
        'KYD' => 'Dólar caimano (de Islas Caimán)',
        'KZT' => 'Tenge kazajo',
        'LAK' => 'Kip lao',
        'LBP' => 'Libra libanesa',
        'LKR' => 'Rupia de Sri Lanka',
        'LRD' => 'Dólar liberiano',
        'LSL' => 'Loti lesotense',
        'LTL' => 'Litas lituano',
        'LVL' => 'Lat letón',
        'LYD' => 'Dinar libio',

        // --- PÁGINA 3 ---
        'MAD' => 'Dirham marroquí',
        'MDL' => 'Leu moldavo',
        'MGA' => 'Ariary malgache',
        'MKD' => 'Denar macedonio',
        'MMK' => 'Kyat birmano',
        'MNT' => 'Tughrik mongol',
        'MOP' => 'Pataca de Macao',
        'MRO' => 'Ouguiya mauritana',
        'MTL' => 'Lira maltesa',
        'MUR' => 'Rupia mauricia',
        'MVR' => 'Rufiyaa maldiva',
        'MWK' => 'Kwacha malauí',
        'MXN' => 'Peso mexicano',
        'MXV' => 'Unidad de Inversión (UDI) mexicana (código de fondos)',
        'MYR' => 'Ringgit malayo',
        'MZN' => 'Metical mozambiqueño',
        'NAD' => 'Dólar namibio',
        'NGN' => 'Naira nigeriana',
        'NIO' => 'Córdoba nicaragüense',
        'NOK' => 'Corona noruega',
        'NPR' => 'Rupia nepalesa',
        'NZD' => 'Dólar neozelandés',
        'OMR' => 'Rial omaní',
        'PAB' => 'Balboa panameña',
        'PEN' => 'Nuevo sol peruano',
        'PGK' => 'Kina de Papúa Nueva Guinea',
        'PHP' => 'Peso filipino',
        'PKR' => 'Rupia pakistaní',
        'PLN' => 'zloty polaco',
        'PYG' => 'Guaraní paraguayo',
        'QAR' => 'Rial qatarí',
        'RON' => 'Leu rumano',
        'RUB' => 'Rublo ruso',
        'RWF' => 'Franco ruandés',
        'SAR' => 'Riyal saudí',
        'SBD' => 'Dólar de las Islas Salomón',
        'SCR' => 'Rupia de Seychelles',
        'SDG' => 'Dinar sudanés',
        'SEK' => 'Corona sueca',
        'SGD' => 'Dólar de Singapur',
        'SHP' => 'Libra de Santa Helena',
        'SKK' => 'Corona eslovaca',
        'SLL' => 'Leone de Sierra Leona',
        'SOS' => 'Chelín somalí',
        'SRD' => 'Dólar surinamés',
        'STD' => 'Dobra de Santo Tomé y Príncipe',
        'SYP' => 'Libra siria',

        // --- PÁGINA 4 ---
        'SZL' => 'Lilangeni suazi',
        'THB' => 'Baht tailandés',
        'TJS' => 'Somoni tayik (de Tayikistán)',
        'TMT' => 'Manat turcomano',
        'TND' => 'Dinar tunecino',
        'TOP' => 'Pa\'anga tongano',
        'TRY' => 'Lira turca',
        'TTD' => 'Dólar de Trinidad y Tobago',
        'TWD' => 'Dólar taiwanés',
        'TZS' => 'Chelín tanzano',
        'UAH' => 'Grivna ucraniana',
        'UGX' => 'Chelín ugandés',
        'USD' => 'Dólar estadounidense',
        'USN' => 'Dólar estadounidense (Siguiente día) (código de fondos)',
        'USS' => 'Dólar estadounidense (Mismo día) (código de fondos)',
        'UYU' => 'Peso uruguayo',
        'UZS' => 'Som uzbeko',
        'VEF' => 'Bolívar fuerte venezolano',
        'VND' => 'Dong vietnamita',
        'VUV' => 'Vatu vanuatense',
        'WST' => 'Tala samoana',
        'XAF' => 'Franco CFA de África Central',
        'XAG' => 'Onza de plata',
        'XAU' => 'Onza de oro',
        'XBA' => 'European Composite Unit (EURCO) (unidad del mercado de bonos)',
        'XBB' => 'European Monetary Unit (E.M.U.-6) (unidad del mercado de bonos)',
        'XBC' => 'European Unit of Account 9 (E.U.A.-9) (unidad del mercado de bonos)',
        'XBD' => 'European Unit of Account 17 (E.U.A.-17) (unidad del mercado de bonos)',
        'XCD' => 'Dólar del Caribe Oriental',
        'XDR' => 'Derechos Especiales de Giro (FMI)',
        'XFO' => 'Franco de oro (Special settlement currency)',
        'XFU' => 'Franco UIC (Special settlement currency)',
        'XOF' => 'Franco CFA de África Occidental',
        'XPD' => 'Onza de paladio',
        'XPF' => 'Franco CFP',
        'XPT' => 'Onza de platino',
        'XTS' => 'Reservado para pruebas',
        'XXX' => 'Sin divisa',
        'YER' => 'Rial yemení (de Yemen)',
        'ZAR' => 'Rand sudafricano',
        'ZMK' => 'Kwacha zambiano',
        'ZWL' => 'Dólar zimbabuense',
    ];
    public static $metodosValoracion = [
        'VALADU.VTM' => 'Valor de transacción',
        'VALADU.VMI' => 'Valor de transacción de las mercancías idénticas',
        'VALADU.VMS' => 'Valor de transacción de las mercancías similares',
        'VALADU.VPU' => 'Valor de precio unitario de venta',
        'VALADU.VR'  => 'Valor reconstruido de las mercancías importadas',
        'VALADU.A78' => 'Valor determinado conforme a lo establecido en el artículo 78',
    ];
    public static $formasPago = [
        'FORPAG.EF' => 'Efectivo',
        'FORPAG.TE' => 'Transferencia electrónica',
        'FORPAG.LC' => 'Letra de cambio',
        'FORPAG.CC' => 'Carta de crédito',
        'FORPAG.CH' => 'Cheque',
        'FORPAG.OT' => 'Otro tipo de pago',
    ];
    public static $incrementables = [
        'INCRE.CG' => 'Comisiones y gastos de corretaje, excepto comisiones de compra.',
        'INCRE.CE' => 'Costo de los envases o embalajes que formen un todo con las mercancías.',
        'INCRE.GT' => 'Gastos de embalaje (mano de obra y/o materiales).',
        'INCRE.GS' => 'Gastos de transporte, seguros y conexos erogados antes del arribo.',
        'INCRE.MP' => 'Materiales, piezas y artículos incorporados a las mercancías.',
        'INCRE.HM' => 'Herramientas, matrices y moldes para la producción.',
        'INCRE.MC' => 'Materiales consumidos en la producción.',
        'INCRE.TI' => 'Trabajos de ingeniería, diseños y planos realizados fuera del país.',
        'INCRE.RD' => 'Regalías y derechos de licencia a pagar como condición de venta.',
        'INCRE.VC' => 'Valor de cualquier parte del producto que se revierta al vendedor.',
    ];
    public static $decrementables = [
        'DECRE.GR' => 'Gastos realizados por cuenta del importador', 
        'DECRE.RP' => 'Los realizados posteriores a la importación por construcción, instalación, armado, montaje, mantenimiento o asistencia técnica.', 
        'DECRE.GT' => 'Gastos de transporte, seguros y conexos (como manejo, carga y descarga) erogados con posterioridad a que se den los momentos señalados en el artículo 56, fracción I de la Ley.', 
        'DECRE.RC' => 'Los realizados por contribuciones y cuotas compensatorias aplicables en territorio nacional por la importación o enajenación', 
        'DECRE.PI' => 'Pagos del importador al vendedor por dividendos u otros que no guarden relación directa con las mercancías importadas.',
        'DECRE.ID' => 'Información de descuentos especiales para aplicar en el momento de la compraventa', 
    ];
    public static $incoterms = [
        'TIPINC.CFR' => 'CFR - COSTE Y FLETE (PUERTO DE DESTINO CONVENIDO).',
        'TIPINC.CIF' => 'CIF - COSTE, SEGURO Y FLETE (PUERTO DE DESTINO CONVENIDO).',
        'TIPINC.CPT' => 'CPT - TRANSPORTE PAGADO HASTA (EL LUGAR DE DESTINO CONVENIDO).',
        'TIPINC.CIP' => 'CIP - TRANSPORTE Y SEGURO PAGADOS HASTA (LUGAR DE DESTINO CONVENIDO).',
        'TIPINC.DAP' => 'DAP - ENTREGADA EN LUGAR.',
        'TIPINC.DDP' => 'DDP - ENTREGADA DERECHOS PAGADOS (LUGAR DE DESTINO CONVENIDO).',
        'TIPINC.DPU' => 'DPU - ENTREGADA Y DESCARGADA EN EL LUGAR ACORDADO.',
        'TIPINC.EXW' => 'EXW - EN FABRICA (LUGAR CONVENIDO).',
        'TIPINC.FCA' => 'FCA - FRANCO TRANSPORTISTA (LUGAR DESIGNADO).',
        'TIPINC.FAS' => 'FAS - FRANCO AL COSTADO DEL BUQUE (PUERTO DE CARGA CONVENIDO).',
        'TIPINC.FOB' => 'FOB - FRANCO A BORDO (PUERTO DE CARGA CONVENIDO).',
        'TIPINC.DAF' => 'DAF - ENTREGADA EN FRONTERA (LUGAR CONVENIDO).',
        'TIPINC.DAT' => 'DAT - ENTREGADA EN TERMINAL.',
        'TIPINC.DES' => 'DES - ENTREGADA SOBRE BUQUE (PUERTO DE DESTINO CONVENIDO).',
        'TIPINC.DEQ' => 'DEQ - ENTREGADA EN MUELLE (PUERTO DE DESTINO CONVENIDO).',
        'TIPINC.DDU' => 'DDU - ENTREGADA DERECHOS NO PAGADOS (LUGAR DE DESTINO CONVENIDO).',
    ];
    public static $tiposFigura = [
        'TIPFIG.AGE' => 'Agente Aduanal', 
        'TIPFIG.AAD' => 'Agencia Aduanal', 
        'TIPFIG.REP' => 'Representante Legal', 
        'TIPFIG.OTR' => 'Otro', 
    ];

    public static $aduanas = [
        '01-0' => '01-0 - ACAPULCO, ACAPULCO DE JUÁREZ, GUERRERO.',
        '01-2' => '01-2 - AEROPUERTO INTERNACIONAL GENERAL JUAN N. ÁLVAREZ, ACAPULCO, GUERRERO.',
        '02-0' => '02-0 - AGUA PRIETA, AGUA PRIETA, SONORA.',
        '05-0' => '05-0 - SUBTENIENTE LÓPEZ, SUBTENIENTE LÓPEZ, QUINTANA ROO.',
        '05-1' => '05-1 - SUBTENIENTE LÓPEZ II "CHACTEMAL", OTHÓN P. BLANCO, CHETUMAL, QUINTANA ROO.',
        '06-0' => '06-0 - CIUDAD DEL CARMEN, CIUDAD DEL CARMEN, CAMPECHE.',
        '06-3' => '06-3 - SEYBAPLAYA, CHAMPOTÓN, CAMPECHE.',
        '07-0' => '07-0 - CIUDAD JUÁREZ, JUÁREZ, CHIHUAHUA.',
        '07-1' => '07-1 - PUENTE INTERNACIONAL ZARAGOZA ISLETA, JUÁREZ, CHIHUAHUA.',
        '07-2' => '07-2 - SAN JERÓNIMO-SANTA TERESA, JUÁREZ, CHIHUAHUA.',
        '07-3' => '07-3 - AEROPUERTO INTERNACIONAL ABRAHAM GONZÁLEZ, JUÁREZ, CHIHUAHUA.',
        '07-4' => '07-4 - GUADALUPE-TORNILLO, GUADALUPE, CHIHUAHUA.',
        '08-0' => '08-0 - COATZACOALCOS, COATZACOALCOS, VERACRUZ.',
        '11-0' => '11-0 - ENSENADA, ENSENADA, BAJA CALIFORNIA.',
        '12-0' => '12-0 - GUAYMAS, GUAYMAS, SONORA.',
        '14-0' => '14-0 - LA PAZ, LA PAZ, BAJA CALIFORNIA SUR.',
        '14-2' => '14-2 - SAN JOSÉ DEL CABO, LOS CABOS, BAJA CALIFORNIA SUR.',
        '14-4' => '14-4 - SANTA ROSALÍA, MULEGÉ, BAJA CALIFORNIA SUR.',
        '14-7' => '14-7 - PICHILINGÜE, LA PAZ, BAJA CALIFORNIA SUR.',
        '16-0' => '16-0 - MANZANILLO, MANZANILLO, COLIMA.',
        '16-1' => '16-1 - ARMERÍA, ARMERÍA, COLIMA.',
        '17-0' => '17-0 - MATAMOROS, MATAMOROS, TAMAULIPAS.',
        '17-1' => '17-1 - LUCIO BLANCO-LOS INDIOS, MATAMOROS, TAMAULIPAS.',
        '17-2' => '17-2 - FERROVIARIA DE MATAMOROS, MATAMOROS, TAMAULIPAS.',
        '18-0' => '18-0 - MAZATLÁN, MAZATLÁN, SINALOA.',
        '18-3' => '18-3 - TOPOLOBAMPO, AHOME, SINALOA.',
        '19-0' => '19-0 - MEXICALI, MEXICALI, BAJA CALIFORNIA.',
        '19-2' => '19-2 - LOS ALGODONES, MEXICALI, BAJA CALIFORNIA.',
        '19-3' => '19-3 - SAN FELIPE, MEXICALI, BAJA CALIFORNIA.',
        '20-0' => '20-0 - MÉXICO, CIUDAD DE MÉXICO.',
        '20-2' => '20-2 - IMPORTACIÓN Y EXPORTACIÓN DE CONTENEDORES, ALCALDÍA AZCAPOTZALCO, CIUDAD DE MÉXICO.',
        '22-0' => '22-0 - NACO, NACO, SONORA.',
        '23-0' => '23-0 - NOGALES, NOGALES, SONORA.',
        '23-1' => '23-1 - SÁSABE, SÁRIC, SONORA.',
        '23-2' => '23-2 - AEROPUERTO INTERNACIONAL GENERAL IGNACIO PESQUEIRA GARCÍA, HERMOSILLO, SONORA.',
        '23-3' => '23-3 - CIUDAD OBREGÓN ADYACENTE AL AEROPUERTO DE CIUDAD OBREGÓN, CAJEME, SONORA.',
        '23-4' => '23-4 - AEROPUERTO INTERNACIONAL DE CULIACÁN, CULIACÁN, SINALOA.',
        '24-0' => '24-0 - NUEVO LAREDO, NUEVO LAREDO, TAMAULIPAS.',
        '25-0' => '25-0 - OJINAGA, OJINAGA, CHIHUAHUA.',
        '26-0' => '26-0 - PUERTO PALOMAS, PUERTO PALOMAS, CHIHUAHUA.',
        '27-0' => '27-0 - PIEDRAS NEGRAS, PIEDRAS NEGRAS, COAHUILA DE ZARAGOZA.',
        '27-1' => '27-1 - AEROPUERTO INTERNACIONAL PLAN DE GUADALUPE, RAMOS ARIZPE, COAHUILA DE ZARAGOZA.',
        '28-0' => '28-0 - PROGRESO, PROGRESO, YUCATÁN.',
        '28-2' => '28-2 - AEROPUERTO INTERNACIONAL LIC. MANUEL CRESCENCIO REJÓN, MÉRIDA, YUCATÁN.',
        '30-0' => '30-0 - CIUDAD REYNOSA, REYNOSA, TAMAULIPAS.',
        '30-2' => '30-2 - LAS FLORES, RÍO BRAVO, TAMAULIPAS.',
        '30-4' => '30-4 - AEROPUERTO INTERNACIONAL GENERAL. LUCIO BLANCO, REYNOSA, TAMAULIPAS.',
        '30-5' => '30-5 - RÍO BRAVO-DONNA, RÍO BRAVO, TAMAULIPAS.',
        '30-6' => '30-6 - ANZALDÚAS, REYNOSA, TAMAULIPAS.',
        '30-7' => '30-7 - AEROPUERTO INTERNACIONAL GENERAL PEDRO JOSÉ MÉNDEZ, VICTORIA, TAMAULIPAS.',
        '31-0' => '31-0 - SALINA CRUZ, SALINA CRUZ, OAXACA.',
        '31-3' => '31-3 - PUERTO CHIAPAS, TAPACHULA, CHIAPAS.',
        '33-0' => '33-0 - SAN LUIS RÍO COLORADO, SAN LUIS RÍO COLORADO, SONORA.',
        '34-0' => '34-0 - CIUDAD MIGUEL ALEMÁN, MIGUEL ALEMÁN, TAMAULIPAS.',
        '34-2' => '34-2 - GUERRERO, GUERRERO, TAMAULIPAS.',
        '37-0' => '37-0 - CIUDAD HIDALGO, CIUDAD HIDALGO, CHIAPAS.',
        '37-2' => '37-2 - CIUDAD TALISMÁN, TUXTLA CHICO, CHIAPAS.',
        '37-3' => '37-3 - AEROPUERTO INTERNACIONAL DE OAXACA, SANTA CRUZ XOXOCOTLÁN, OAXACA.',
        '37-4' => '37-4 - AEROPUERTO INTERNACIONAL C.P.A. CARLOS ROVIROSA PÉREZ, CIUDAD DE VILLAHERMOSA, CENTRO, TABASCO.',
        '37-6' => '37-6 - CIUDAD CUAUHTÉMOC, FRONTERA COMALAPA, CHIAPAS.',
        '37-7' => '37-7 - EL CEIBO, TENOSIQUE, TABASCO.',
        '37-8' => '37-8 - CRUCE FRONTERIZO NUEVO ORIZABA-INGENIEROS, BENEMÉRITO DE LAS AMÉRICAS, CHIAPAS.',
        '38-0' => '38-0 - TAMPICO, TAMPICO, TAMAULIPAS.',
        '39-0' => '39-0 - TECATE, TECATE, BAJA CALIFORNIA.',
        '39-1' => '39-1 - LORETO, LORETO, BAJA CALIFORNIA SUR.',
        '39-2' => '39-2 - CABO SAN LUCAS, LOS CABOS, BAJA CALIFORNIA SUR.',
        '40-0' => '40-0 - TIJUANA, TIJUANA, BAJA CALIFORNIA.',
        '40-2' => '40-2 - AEROPUERTO INTERNACIONAL DENOMINADO ABELARDO L. RODRÍGUEZ, TIJUANA, BAJA CALIFORNIA.',
        '42-0' => '42-0 - TUXPAN, TUXPAN DE RODRÍGUEZ CANO, VERACRUZ.',
        '42-1' => '42-1 - TUXPAN, TUXPAN, VERACRUZ.',
        '43-0' => '43-0 - VERACRUZ, VERACRUZ, VERACRUZ.',
        '43-2' => '43-2 - AEROPUERTO INTERNACIONAL GENERAL HERIBERTO JARA CORONA, VERACRUZ, VERACRUZ.',
        '44-0' => '44-0 - CIUDAD ACUÑA, CIUDAD ACUÑA, COAHUILA DE ZARAGOZA.',
        '46-0' => '46-0 - TORREÓN, TORREÓN, COAHUILA DE ZARAGOZA.',
        '46-1' => '46-1 - AEROPUERTO DE TORREÓN, COAHUILA DE ZARAGOZA.',
        '46-2' => '46-2 - GÓMEZ PALACIO, GÓMEZ PALACIO, DURANGO.',
        '46-3' => '46-3 - AEROPUERTO INTERNACIONAL GENERAL GUADALUPE VICTORIA, DURANGO, DURANGO.',
        '47-0' => '47-0 - AEROPUERTO INTERNACIONAL DE LA CIUDAD DE MÉXICO. (Nota 1) (Decreto que establece el cierre del AICM Benito Juárez, para las operaciones del servicio al público de transporte aéreo que se indica, DOF 3/II/2023',
        '47-1' => '47-1 - SATÉLITE, PARA IMPORTACIÓN Y EXPORTACIÓN POR VÍA AÉREA, AEROPUERTO INTERNACIONAL "BENITO JUÁREZ" DE LA CIUDAD DE MÉXICO.',
        '47-2' => '47-2 - CENTRO POSTAL MECANIZADO, POR VÍA POSTAL Y POR TRÁFICO AÉREO, AEROPUERTO INTERNACIONAL "BENITO JUÁREZ" DE LA CIUDAD DE MÉXICO.',
        '48-0' => '48-0 - GUADALAJARA, TLAJOMULCO DE ZÚÑIGA, JALISCO.',
        '48-1' => '48-1 - PUERTO VALLARTA, PUERTO VALLARTA, JALISCO.',
        '48-4' => '48-4 - TERMINAL INTERMODAL FERROVIARIA, GUADALAJARA, JALISCO.',
        '50-0' => '50-0 - SONOYTA, SONOYTA, SONORA.',
        '50-1' => '50-1 - SAN EMETERIO, GENERAL PLUTARCO ELÍAS CALLES, SONORA.',
        '51-0' => '51-0 - LÁZARO CÁRDENAS, LÁZARO CÁRDENAS, MICHOACÁN.',
        '51-1' => '51-1 - AEROPUERTO INTERNACIONAL IXTAPA-ZIHUATANEJO, ZIHUATANEJO DE AZUETA, GUERRERO.',
        '52-0' => '52-0 - MONTERREY, GENERAL MARIANO ESCOBEDO, NUEVO LEÓN.',
        '52-1' => '52-1 - AEROPUERTO INTERNACIONAL GENERAL MARIANO ESCOBEDO, APODACA, NUEVO LEÓN.',
        '52-3' => '52-3 - SALINAS VICTORIA A (TERMINAL FERROVIARIA), SALINAS VICTORIA, NUEVO LEÓN.',
        '52-4' => '52-4 - GENERAL ESCOBEDO, GENERAL ESCOBEDO, NUEVO LEÓN.',
        '52-5' => '52-5 - SALINAS VICTORIA B (INTERPUERTO), SALINAS VICTORIA, NUEVO LEÓN.',
        '53-0' => '53-0 - CANCÚN, CANCÚN, QUINTANA ROO.',
        '53-2' => '53-2 - AEROPUERTO INTERNACIONAL DE COZUMEL, COZUMEL, QUINTANA ROO.',
        '53-3' => '53-3 - PUERTO MORELOS, BENITO JUÁREZ, QUINTANA ROO.',
        '64-0' => '64-0 - QUERÉTARO, EL MARQUES Y COLÓN, QUERÉTARO.',
        '64-7' => '64-7 - HIDALGO, ATOTONILCO DE TULA, HIDALGO.',
        '65-0' => '65-0 - TOLUCA, TOLUCA, ESTADO DE MÉXICO.',
        '65-1' => '65-1 - SAN CAYETANO MORELOS, TOLUCA, ESTADO DE MÉXICO.',
        '67-0' => '67-0 - CHIHUAHUA, CHIHUAHUA, CHIHUAHUA.',
        '67-2' => '67-2 - AEROPUERTO INTERNACIONAL GENERAL ROBERTO FIERRO VILLALOBOS, CHIHUAHUA, CHIHUAHUA.',
        '73-0' => '73-0 - AGUASCALIENTES, SAN FRANCISCO DE LOS ROMO, AGUASCALIENTES.',
        '73-1' => '73-1 - PARQUE MULTIMODAL INTERPUERTO, SAN LUIS POTOSÍ, SAN LUIS POTOSÍ.',
        '73-2' => '73-2 - AEROPUERTO INTERNACIONAL GENERAL LEOBARDO C. RUIZ, EN CALERA, ZACATECAS.',
        '73-3' => '73-3 - AEROPUERTO INTERNACIONAL PONCIANO ARRIAGA, SOLEDAD DE GRACIANO SÁNCHEZ, SAN LUIS POTOSÍ.',
        '73-4' => '73-4 - LA PILA-VILLA, VILLA DE REYES, SAN LUIS POTOSÍ.',
        '73-5' => '73-5 - AEROPUERTO INTERNACIONAL LIC. JESÚS TERÁN PEREDO, AGUASCALIENTES, AGUASCALIENTES.',
        '75-0' => '75-0 - PUEBLA, HEROICA PUEBLA DE ZARAGOZA, PUEBLA.',
        '75-1' => '75-1 - CUERNAVACA, JIUTEPEC, MORELOS.',
        '75-4' => '75-4 - AEROPUERTO INTERNACIONAL HERMANOS SERDÁN, HUEJOTZINGO, PUEBLA.',
        '80-0' => '80-0 - COLOMBIA, COLOMBIA, NUEVO LEÓN.',
        '81-0' => '81-0 - ALTAMIRA, ALTAMIRA, TAMAULIPAS.',
        '82-0' => '82-0 - CIUDAD CAMARGO, CAMARGO, TAMAULIPAS.',
        '83-0' => '83-0 - DOS BOCAS, PARAÍSO, TABASCO.',
        '84-0' => '84-0 - GUANAJUATO, SILAO DE LA VICTORIA, GUANAJUATO.',
        '84-1' => '84-1 - CELAYA, CELAYA, GUANAJUATO.',
        '84-2' => '84-2 - AEROPUERTO INTERNACIONAL DE GUANAJUATO, SILAO DE LA VICTORIA, GUANAJUATO.',
        '85-0' => '85-0 - AEROPUERTO INTERNACIONAL FELIPE ÁNGELES, SANTA LUCÍA, ZUMPANGO, ESTADO DE MÉXICO.',
    ];

    /**
     * Tipos de Documento aceptados por VUCEM para digitalización.
     * Catálogo oficial según documentación VUCEM 2026
     */
    public static $tiposDocumento = [
        // Documentos más comunes (ordenados primero)
        '170' => 'Factura o CFDI',
        '177' => 'Identificación Oficial',
        '172' => 'Contratos',
        '171' => 'Documento con el que se acredite la propiedad de la mercancía',
        '179' => 'Comprobante de domicilio',
        '180' => 'Documento que ampare el avalúo de las mercancías',
        '189' => 'Actas',
        '192' => 'Escritos',
        '360' => 'Documento complementario',
        
        // Documentos de comercio exterior
        '168' => 'Calca o fotografía digital del NIV del vehículo',
        '169' => 'Aviso / Certificado de Exportación de Tequila',
        '176' => 'Documentación relacionada con garantía (artículos 84-A y 86-A de la L.A.)',
        '185' => 'Documentos de adjudicación judicial de las mercancías',
        '187' => 'Solicitud de retiro de mercancías que causaron abandono',
        
        // Certificados y comprobantes
        '420' => 'Certificado de peso o volumen',
        '421' => 'Comprobante de importación temporal de embarcación debidamente formalizado',
        '422' => 'Comprobante expedido por donataria',
        '423' => 'Consulta que el vehículo no está reportado robado/siniestrado/restringido',
        '424' => 'Clave Única del Registro de Población (CURP)',
        
        // Declaraciones
        '425' => 'Declaración de internación/extracción de cantidades en efectivo y/o documentos por cobrar',
        '426' => 'Declaración de operaciones que no confieren origen (países no parte del TLCI)',
        '427' => 'Declaración de motivos de devolución de mercancías (regla 3.8.9)',
        
        // Documentación especial
        '428' => 'Documentación para identificación, análisis y control (artículo 36-A de la L.A.)',
        '429' => 'Documento que acredite que acepta y subsana la irregularidad',
        '430' => 'Documentación que ampare la importación temporal del vehículo',
        '431' => 'Documentación que compruebe adquisición de mercancías bajo Programa IMMEX',
        '433' => 'Documento que determine la procedencia y el origen de las mercancías',
        '434' => 'Documento que acredite el reintegro del IVA (devolución/acreditamiento)',
        '435' => 'Documentos previstos en la regla 8.7, fracciones I a IV del TLCAN',
        '436' => 'Documento que compruebe cumplimiento de regulaciones no arancelarias',
        '438' => 'Conocimiento de embarque, lista de empaque, guía u otros documentos de transporte',
        '439' => 'Hoja con datos de matrícula y nombre del barco (mercancía almacenada)',
        '440' => 'Manifiesto de carga',
        '442' => 'Pedimentos',
        '443' => 'Programa IMMEX',
        '444' => 'Relación de candados',
        '445' => 'Relación de certificados de origen',
        
        // Otros documentos del catálogo anterior
        '047' => 'Pago de Derechos',
        '112' => 'Acta Constitutiva',
        '368' => 'Otros (Documento Universal)',
        '441' => 'Oficios emitidos por autoridad',
        '479' => 'Lista de Empaque',
    ];

    /**
     * Tipos de Documento específicos para Manifestación de Valor (MVE)
     * Según Artículo 81 del Reglamento de la Ley Aduanera
     */
    public static $tiposDocumentoMve = [
        // I. Factura comercial
        '170' => 'I. Factura comercial (CFDI)',
        
        // II. Conocimiento de embarque, lista de empaque, guía aérea o demás documentos de transporte
        '438' => 'II. Conocimiento de embarque, guía aérea o documento de transporte',
        '479' => 'II. Lista de Empaque',
        
        // III. El que compruebe el origen cuando corresponda, y la procedencia de las mercancías
        '433' => 'III. Documento que determina procedencia y origen de mercancías',
        '445' => 'III. Relación de certificados de origen',
        
        // IV. En el que conste la garantía (artículo 36-A de la Ley)
        '176' => 'IV. Documentación relacionada con garantía (art. 36-A L.A.)',
        
        // V. En el que conste el pago de las Mercancías (transferencia, carta de crédito)
        '360' => 'V. Comprobante de pago de mercancías (transferencia/carta de crédito)',
        
        // VI. El relativo a los gastos de transporte, seguros y gastos conexos
        '172' => 'VI. Gastos de transporte, seguros y gastos conexos',
        
        // VII. Contratos relacionados con la transacción de la Mercancía
        '171' => 'VII. Contratos relacionados con la transacción de mercancía',
        
        // VIII. Los que soporten los conceptos incrementables (Artículo 65 de la Ley)
        '180' => 'VIII. Documento que soporte conceptos incrementables (art. 65)',
        
        // IX. Cualquier otra información y documentación necesaria
        '368' => 'IX. Otros - Documentación adicional para valor en aduana',
    ];
}